@startuml procesos
start
:Mesero ingresa pedido en el sistema;
:Sistema consulta inventario en tiempo real;
:Sistema consulta BD_delicias para verificar inventario;
if (¿Ingredientes disponibles?) then (Sí)
    :Sistema genera número de pedido;
    :Enviar pedido a la cocina;
    :Cocina prepara el pedido;
    :Actualizar estado del pedido;
else (No)
    :Notificar al mesero sobre falta de ingredientes;
    :Mesero consulta al cliente sobre alternativas;
    if (¿Cliente acepta alternativas?) then (Sí)
        :Volver al paso de "Ingredientes disponibles?";
    else (No)
        :Cancelar pedido;
        :Actualizar estado del pedido a "cancelado";
        :Generar notificación al administrador;
        if (¿Administrador suspende platillo?) then (Sí)
            :No ofrecer platillo por el momento;
        else (No)
            :Solicitar reposición de ingredientes;
            :Inventario solicita actualización de inventario a BD_delicias;
            :BD_delicias confirma actualización;
        endif
        :Notificar reposición de ingredientes;
        :Mesero notifica al cliente sobre el retraso;
    endif
endif
:Estado del pedido actualizado a "listo para servir";
:Mesero recibe el pedido preparado;

stop
@enduml


